// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuneErrorInfo } from "./RuneErrorInfo";

export type ErrorEvent = { message: string, rune_error_info: RuneErrorInfo | null, };
